name: OIDC Debug

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Debug OIDC token
        uses: github/actions-oidc-debugger@main
